// Generated by LiveScript 1.3.1
(function(){
  chrome.storage.local.set({
    name: "CSCI4140",
    message: "tywong sosad"
  }, function(e){});
  chrome.storage.local.get(null, function(e){});
}).call(this);
