// Generated by LiveScript 1.3.1
(function(){
  chrome.storage.local.get(null, function(storage){
    debugger;
    var allFields, findAndFill, ref$, form, error;
    allFields = ['Captcha Picture ID', 'Captcha Input Field ID'];
    findAndFill = function(id, value){
      value == null && (value = '');
      return document.getElementById(storage[id]).value = storage[value];
    };
    try {
      findAndFill('Login Name Field ID', 'Login Name Field Value');
      findAndFill('Password Field ID', 'Password Field Value');
      if (storage['Auto Submit']) {
        if ((ref$ = document.getElementsByClassName('alert alert-danger')) != null && ref$.length) {
          alert('Auto login failed');
          return;
        }
        form = document.getElementById(storage['Form ID']);
        return form.submit();
      }
    } catch (e$) {
      return error = e$;
    }
  });
}).call(this);
