// Generated by LiveScript 1.3.1
(function(){
  chrome.storage.local.get(null, function(storage){
    var allFields, makeDiv, makeField, makeContent, makeFields, messageArea, addForm, saveForm, saveAndFillForm;
    allFields = ['Form ID', 'Login Name Field ID', 'Login Name Field Value', 'Password Field ID', 'Password Field Value', 'Captcha Picture ID', 'Captcha Input Field ID'];
    makeDiv = function(){
      return document.createElement('div');
    };
    makeField = function(name, type){
      var div;
      type == null && (type = 'text');
      div = makeDiv();
      makeContent(name, type).forEach(bind$(div, 'appendChild'));
      return div;
    };
    makeContent = function(name, type){
      var ref$;
      type == null && (type = 'text');
      return [(ref$ = document.createElement('span'), ref$.innerHTML = name, ref$), (ref$ = document.createElement('input'), ref$.type = type, ref$.value = storage[name] || '', ref$.id = name, ref$.checked = type === 'checkbox' ? storage[name] : '', ref$)];
    };
    makeFields = function(){
      return allFields.map(makeField);
    };
    messageArea = null;
    addForm = function(container){
      var ref$;
      makeFields().forEach(bind$(container, 'appendChild'));
      container.appendChild(makeField('Auto Submit', 'checkbox'));
      container.appendChild((ref$ = document.createElement('button'), ref$.innerHTML = 'Save', ref$.onclick = saveForm, ref$));
      container.appendChild((ref$ = document.createElement('button'), ref$.innerHTML = 'Save and fill button', ref$.onclick = saveAndFillForm, ref$));
      return container.appendChild(messageArea = (ref$ = document.createElement('pre'), ref$.innerHTML = 'This is the message area\n', ref$));
    };
    saveForm = function(cb){
      var values;
      values = {};
      allFields.forEach(function(f){
        return values[f] = document.getElementById(f).value;
      });
      values['Auto Submit'] = document.getElementById('Auto Submit').checked;
      return chrome.storage.local.set(values, function(e){
        if (typeof cb == 'function') {
          cb(e);
        }
        return messageArea != null ? messageArea.innerHTML += "Saved Successfully\n" : void 8;
      });
    };
    saveAndFillForm = function(cb){
      saveForm(cb);
      return chrome.tabs.query({
        active: true,
        currentWindow: true
      }, function(tabs){
        var ref$;
        return chrome.tabs.sendMessage(tabs != null ? (ref$ = tabs[0]) != null ? ref$.id : void 8 : void 8, {
          command: 'fill'
        }, function(response){
          return messageArea != null ? messageArea.innerHTML += "Filled in\n" : void 8;
        });
      });
    };
    return addForm(document.body);
  });
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
}).call(this);
